from fpdf import FPDF
from datetime import datetime
import sqlite3
import os

db_path = r'c:\Users\dhanu\OneDrive\Desktop\8Th sem\city\backend\smart_city.db'
pdf_path = r'c:\Users\dhanu\OneDrive\Desktop\8Th sem\city\Bengaluru_AI_Incident_Report.pdf'

class PDFReport(FPDF):
    def header(self):
        # Header - Urban Intelligence
        self.set_font('Arial', 'B', 16)
        self.set_text_color(41, 128, 185) # Blue
        self.cell(0, 10, 'CITYPULSE URBAN INTELLIGENCE PLATFORM', 0, 1, 'C')
        
        self.set_font('Arial', 'I', 11)
        self.set_text_color(100, 100, 100)
        self.cell(0, 8, 'Generated by Vanguard AI Core (Gemini Analysis)', 0, 1, 'C')
        
        self.set_font('Arial', '', 10)
        self.cell(0, 6, f'Date of Report: {datetime.now().strftime("%B %d, %Y - %I:%M %p")}', 0, 1, 'C')
        self.line(10, 35, 200, 35)
        self.ln(15)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.set_text_color(150, 150, 150)
        self.cell(0, 10, f'Page {self.page_no()}', 0, 0, 'C')

def fetch_events_from_db():
    if not os.path.exists(db_path):
        return []
    conn = sqlite3.connect(db_path)
    cursor = conn.cursor()
    cursor.execute("SELECT title, location_name, event_type, severity, timestamp, description FROM events ORDER BY timestamp DESC LIMIT 40")
    events = cursor.fetchall()
    conn.close()
    return events

def generate_pdf():
    pdf = PDFReport()
    pdf.add_page()
    
    # Report Context
    pdf.set_font('Arial', 'B', 12)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(0, 10, 'AI AGENT PROMPT USED:', 0, 1, 'L')
    pdf.set_font('Courier', '', 9)
    pdf.set_text_color(50, 50, 50)
    prompt_text = "Analyze real-time search queries & social feeds for Bengaluru. Extract the top 40 incidents from 10 categories: \nEmergency, Traffic, Weather, Civic, Public, Crowd, Law & Order, Health, Infrastructure, Transport.\nReturn: Name, Location, Date, Time, and Summary."
    pdf.multi_cell(0, 6, prompt_text)
    pdf.ln(5)

    pdf.set_font('Arial', 'B', 14)
    pdf.set_text_color(41, 128, 185)
    pdf.cell(0, 10, 'LIVE RESULTS: 40 VERIFIED INCIDENTS', 0, 1, 'L')
    pdf.ln(5)

    events = fetch_events_from_db()

    for idx, event in enumerate(events, 1):
        title, loc, e_type, sev, tstamp, desc = event
        
        # Color coding by severity
        if sev.lower() == 'critical':
            pdf.set_text_color(192, 57, 43) # Red
        elif sev.lower() == 'high':
            pdf.set_text_color(211, 84, 0) # Orange
        elif sev.lower() == 'medium':
            pdf.set_text_color(243, 156, 18) # Yellow/Orange
        else:
            pdf.set_text_color(39, 174, 96) # Green
            
        pdf.set_font('Arial', 'B', 11)
        # Handle unicode issues in FPDF
        safe_title = f"{idx}. [{e_type}] {title}".encode('latin-1', 'replace').decode('latin-1')
        pdf.cell(0, 8, safe_title, 0, 1, 'L')
        
        pdf.set_text_color(50, 50, 50)
        pdf.set_font('Arial', '', 10)
        safe_loc = f"Location: {loc}  |  Severity: {sev}  |  Time: {tstamp}".encode('latin-1', 'replace').decode('latin-1')
        pdf.cell(0, 6, safe_loc, 0, 1, 'L')
        
        pdf.set_font('Arial', 'I', 10)
        safe_desc = desc.encode('latin-1', 'replace').decode('latin-1')
        pdf.multi_cell(0, 6, f"Summary: {safe_desc}")
        pdf.ln(3)

    pdf.output(pdf_path)
    print(f"SUCCESS: PDF successfully generated at: {pdf_path}")

if __name__ == "__main__":
    generate_pdf()
